// Generated by scripts/capture-terminal-ui.mjs from OpenClaw f027d7bcf66759cc5408405c7ce1ea023646b879.
export const terminalUiFixtureManifest = Object.freeze({
  "agent-shell": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Five-region agent shell",
    "renderer": "OpenClaw agent TUI · Pi",
    "columns": 80,
    "rows": 24,
    "summary": "OpenClaw agent shell with transcript, status, footer, and editor."
  },
  "agent-composer": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Active multiline composer",
    "renderer": "OpenClaw agent TUI · Pi",
    "columns": 80,
    "rows": 24,
    "summary": "Agent composer containing an unfinished prompt and the terminal cursor."
  },
  "agent-approval": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Workspace skill approval",
    "renderer": "OpenClaw agent TUI · Pi",
    "columns": 80,
    "rows": 24,
    "summary": "Detailed approval with severity, request context, and conservative actions."
  },
  "agent-picker": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Model picker overlay",
    "renderer": "OpenClaw agent TUI · Pi",
    "columns": 80,
    "rows": 24,
    "summary": "Searchable model picker overlay with the current row retained."
  },
  "agent-tool": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Tool execution in transcript",
    "renderer": "OpenClaw agent TUI · Pi",
    "columns": 80,
    "rows": 24,
    "summary": "Assistant text before and after a completed Read File tool row."
  },
  "agent-transcript": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "User and assistant transcript",
    "renderer": "OpenClaw agent TUI · Pi",
    "columns": 80,
    "rows": 24,
    "summary": "User prompt followed by a completed assistant response in the transcript."
  },
  "setup-confirm": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Vertical setup confirmation",
    "renderer": "OpenClaw setup · Clack",
    "columns": 80,
    "rows": 12,
    "summary": "Security acknowledgement with No initially selected and Back available."
  },
  "setup-field-error": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Validated field input",
    "renderer": "OpenClaw setup · Clack",
    "columns": 80,
    "rows": 12,
    "summary": "Gateway port field retaining an invalid value beside its validation message."
  },
  "setup-field-sensitive": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Sensitive field input",
    "renderer": "OpenClaw setup · Clack",
    "columns": 80,
    "rows": 12,
    "summary": "Provider API key input with the entered value masked from terminal output."
  },
  "setup-notices": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Notes and plain output",
    "renderer": "OpenClaw setup · Clack",
    "columns": 80,
    "rows": 16,
    "summary": "Flow intro, titled QuickStart note, unframed disclosure, and outro."
  },
  "setup-flow": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Prompt flow with history",
    "renderer": "OpenClaw setup · Clack",
    "columns": 80,
    "rows": 16,
    "summary": "Intro and note above an active setup prompt with Back and Next navigation."
  },
  "setup-selection": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Single selection with hints",
    "renderer": "OpenClaw setup · Clack",
    "columns": 80,
    "rows": 14,
    "summary": "Setup mode options with initial selection, recommendation copy, and descriptions."
  },
  "setup-multiselect": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Searchable multiple selection",
    "renderer": "OpenClaw setup · Clack",
    "columns": 80,
    "rows": 16,
    "summary": "Searchable hook multiselect with selected values, hints, and filtering."
  },
  "setup-progress": {
    "sourceSha": "f027d7bcf66759cc5408405c7ce1ea023646b879",
    "label": "Active setup progress",
    "renderer": "OpenClaw setup · Clack",
    "columns": 80,
    "rows": 10,
    "summary": "Animated setup progress after its activity label has been updated."
  }
});
